FROM node:14
WORKDIR D:\Github-Repos\i222582_B_Mid\Cafe_Management_System\api-gateway\index.js

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

ENV NAME World

CMD [ "node", "index.js" ]



