networks:
default:
name: CafeMS_App
services:
app: #node
container_name: docker-node
build: .
ports:
- "3000:3000"
environment:
- MONGO_URI=NODE_dbURL
depends_on:
- mongo
networks:
- default
mongo:
container_name: mongo
image: mongo
ports:
- "3000:3000"
volumes:
- mongo_data:/data/db
networks:
- default
volumes:
mongo_data: